services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    environment:
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  engine:
    build: ./engine
    ports:
      - "${ENGINE_PORT}:${ENGINE_PORT}"
    depends_on:
      - db
      - redis
    environment:
      - ENGINE_PORT=${ENGINE_PORT}
    # volumes:
    #   - ./engine:/app
    develop:
      watch:
        - action: sync
          path: ./engine
          target: /app

volumes:
  db_data:
