services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./core/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    environment:
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  engine:
    build: ./core/engine
    ports:
      - "${ENGINE_PORT}:${ENGINE_PORT}"
    depends_on:
      - db
      - redis
    environment:
      - ENGINE_PORT=${ENGINE_PORT}
    volumes:
      - ./core/engine:/usr/src/app
      - /usr/src/app/node_modules

  service-analytics:
    build: ./core/service-analytics
    ports:
      - "${SERVICE_ANALYTICS_PORT}:${SERVICE_ANALYTICS_PORT}"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_URL=redis://redis:${REDIS_PORT}
      - SERVICE_ANALYTICS_PORT=${SERVICE_ANALYTICS_PORT}
    volumes:
      - ./core/service-analytics:/usr/src/app
      - /usr/src/app/node_modules

  api-gateway:
    build: ./core/api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    depends_on:
      - engine
      - service-analytics
    environment:
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - ENGINE_PORT=${ENGINE_PORT}
      - SERVICE_ANALYTICS_PORT=${SERVICE_ANALYTICS_PORT}
    volumes:
      - ./core/api-gateway:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data: